// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(FociDbContext))]
    [Migration("20240919062112_sqlite.local_migration_450")]
    partial class sqlitelocal_migration_450
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("WebApplication1.Models.Meccs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("fordulo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("hazaifelido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("hazainev")
                        .HasColumnType("TEXT");

                    b.Property<int>("haziveg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("vendegfelido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("vendegnev")
                        .HasColumnType("TEXT");

                    b.Property<int>("vendegveg")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Meccsek");
                });
#pragma warning restore 612, 618
        }
    }
}
